name: projectsynthese
description: "Train Your Heart - A simple running tracker."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  geolocator: ^13.0.1
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  local_auth: ^2.3.0
  fl_chart: ^0.69.0
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  screenshot: ^3.0.0
  share_plus: ^10.0.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_g.svg
