// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX_isvMdlJBFifLgb9MCFQycERYVof4_c',
    appId: '1:949300799831:web:fa90dc88b4b2946dc4f612',
    messagingSenderId: '949300799831',
    projectId: 'train-your-heart',
    authDomain: 'train-your-heart.firebaseapp.com',
    storageBucket: 'train-your-heart.firebasestorage.app',
    measurementId: 'G-1JD5XLVYYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkckqbqFqWRiUi-2TUI95bCy4mMCkiFMc',
    appId: '1:949300799831:android:d27b55526723e165c4f612',
    messagingSenderId: '949300799831',
    projectId: 'train-your-heart',
    storageBucket: 'train-your-heart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn59FZUaTZsXjaz-CjXrlAm2_qMJdFfhQ',
    appId: '1:949300799831:ios:6cd274428ffb3899c4f612',
    messagingSenderId: '949300799831',
    projectId: 'train-your-heart',
    storageBucket: 'train-your-heart.firebasestorage.app',
    iosClientId: '949300799831-t6jucmoi7f0bre65s2694egf24h754k5.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectsynthese',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn59FZUaTZsXjaz-CjXrlAm2_qMJdFfhQ',
    appId: '1:949300799831:ios:6cd274428ffb3899c4f612',
    messagingSenderId: '949300799831',
    projectId: 'train-your-heart',
    storageBucket: 'train-your-heart.firebasestorage.app',
    iosClientId: '949300799831-t6jucmoi7f0bre65s2694egf24h754k5.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectsynthese',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX_isvMdlJBFifLgb9MCFQycERYVof4_c',
    appId: '1:949300799831:web:84d4d8237fdf7ec7c4f612',
    messagingSenderId: '949300799831',
    projectId: 'train-your-heart',
    authDomain: 'train-your-heart.firebaseapp.com',
    storageBucket: 'train-your-heart.firebasestorage.app',
    measurementId: 'G-RFHXK5V05L',
  );

}